apiVersion: v1
kind: Service
metadata:
  name: nnrf-nfm
  labels:
    run: nnrf-nfm
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    run: nnrf-nfm
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nnrf-nfm
  namespace: nrf
spec:
  replicas: 3
  selector:
    matchLabels:
      run: nnrf-nfm
  template:
    metadata:
      labels:
        run: nnrf-nfm
    spec:
      containers:
      - name: nnrf-nfm
        image: localhost:32000/nnrf-nfm:registry
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
